[package]
name = "ls-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
owo-colors = "4.2.2"
serde = "1.0.219"
strum = { version = "0.27.2", features = ["derive"] }
tabled = { version = "0.20.0", features = ["derive"] }
